### ISSUE TITLE
Broken links to these docs

### ISSUE THREAD

**Issue by JasonWHowell** [redis/docs#115]
Many links from our site to your docs site broke recently with 404s. 

We have documentation that points to Redis docs pages.  It'd be nice if you can add redirection to fix the issues to prevent 404s when pages move. 

404 recently:
https://redis.io/docs/getting-started/#install-redis
https://redis.io/docs/about/about-stack/
https://redis.io/docs/interact/search-and-query/search/vectors/#creating-a-vss-range-query
https://redis.io/docs/manual/replication/#how-redis-replication-works
https://redis.io/docs/manual/pubsub/
https://docs.redis.com/latest/modules/redisjson/
https://docs.redis.com/latest/modules/redisearch/
https://docs.redis.com/latest/modules/redisbloom/

New links have the same domain, but folder structure must be different throughout the site.
https://redis.io/docs/latest/operate/oss_and_stack/install/

Thanks so much, Jason

**Comment by mich-elle-luna** [comment]
Thanks Jason, much appreciated, here are the equivalents while we work out our redirect problems.

https://redis.io/docs/latest/operate/oss_and_stack/install/install-redis/
https://redis.io/docs/latest/operate/oss_and_stack/install/install-redis/
https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/bloom/
https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/json/
https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/
https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/vectors/#range-queries
https://redis.io/docs/latest/operate/oss_and_stack/management/replication/#how-redis-replication-works
https://redis.io/docs/latest/operate/oss_and_stack/management/replication/#how-redis-replication-works
https://redis.io/docs/latest/develop/interact/pubsub/
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 

</google-sheets-html-origin>

**Comment by mich-elle-luna** [comment]
Hi Jason,

Apologies for these breaking, we are having some problems with the redirects we have in place and are working to resolve it as soon as possible. Thanks for taking the time to provide us with this list, much appreciated. In the meantime, here are the equivalents:

https://redis.io/docs/latest/operate/oss_and_stack/install/install-redis/
https://redis.io/docs/latest/operate/oss_and_stack/install/install-redis/
https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/bloom/
https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/json/
https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/
https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/vectors/#range-queries
https://redis.io/docs/latest/operate/oss_and_stack/management/replication/#how-redis-replication-works
https://redis.io/docs/latest/operate/oss_and_stack/management/replication/#how-redis-replication-works
https://redis.io/docs/latest/develop/interact/pubsub/

-Michelle

**Comment by JasonWHowell** [comment]
Awesome - thanks Michelle!! congrats on the new site look and feel
