### ISSUE TITLE
Broken document link

### ISSUE THREAD

**Issue by JeffreyGroves** [redis/docs#119]
From this article in the KB:

> https://redis.io/kb/doc/2o3ofxrp7w/how-to-enable-ssl-between-a-client-and-redis

there is a broken link in this sentence:

> "Discover how to enable SSL/TLS for clients' connections in the [following document](https://docs.redislabs.com/latest/rs/administering/designing-production/security/tls-configuration/).

The link takes you to:

> https://redis.io/docs/latest/operate/rs/administering/designing-production/security/tls-configuration/

which results in a 404.

Kind regards,

Jeff Groves

**Comment by dmaier-redislabs** [comment]
@dwdougherty I think Mirko worked already on a fix, but please ping him.

**Comment by mich-elle-luna** [comment]
Hi,

Thanks for this report, I believe this page is now at the following link, apologies for the churn we are having with redirecting pages after the migration:
https://redis.io/docs/latest/operate/oss_and_stack/management/security/encryption/

-Michelle

**Comment by dwdougherty** [comment]
I'm told that this issue has been fixed. Please confirm and then close this ticket. Thank you!
