### ISSUE TITLE
rlutil should not be recommended to a customer for use without support participation

### ISSUE THREAD

**Issue by natem-rl** [redis/docs#120]
https://redis.io/kb/doc/2qnr7wvvex/how-to-change-the-cluster-s-master-node

rlutil should never be recommended for customer use without review by Support.

rladmin should be used to change the master node.

https://redis.io/docs/latest/operate/rs/references/cli-utilities/rladmin/cluster/master/

**Comment by dmaier-redislabs** [comment]
@dwdougherty Mirko should take a look here.

**Comment by mich-elle-luna** [comment]
Hi,

Thanks for this report, much appreciated. Related to the cluster master issue, are you asking to remove 'set' from the command example? Should the page document 'cluster master' to identify the master node with no options in the first section? 

-Michelle

**Comment by dwdougherty** [comment]
I'm told this issue is fixed. Please confirm and then close this ticket. Thank you!

**Comment by natem-rl** [comment]
One small issue, in the new text that links to the rladmin documentation, it says "rladmin master cluster" and should instead read "rladmin cluster master".
Additionally, I would recommend giving a full example such as "rladmin cluster master set <node_id>".

**Comment by dwdougherty** [comment]
I just checked and it looks like your latest request was fulfilled. Closing this ticket.
