### ISSUE TITLE
Tutorial content doesn't seem to load correctly

### ISSUE THREAD

**Issue by serinamarie** [redis/docs#122]
Problem: Text isn't populating for tutorials

Example: https://redis.io/learn/howtos/solutions/real-time-inventory/local-inventory-search
<img width="705" alt="Screenshot 2024-04-17 at 5 13 27 PM" src="https://github.com/redis/docs/assets/42048900/49199e7b-66c0-4444-988a-62380bdd62cd">

Apologies if this is not the correct repo for this.

**Comment by dmaier-redislabs** [comment]
@dwdougherty This is for Cody.
