### ISSUE TITLE
Update for openshift OperatorHub  Note: Known Limitation

### ISSUE THREAD

**Issue by hmarrao** [redis/docs#123]
On the note:

_Known Limitation - The automatic use of the security constraint is limited. The Redis Enterprise must be named rec for the constraint to be used automatically. Use the cluster name rec when deploying with the OperatorHub_

one may add: 

**_or ensure that rec yaml  is using the proper rec service account by setting  "rec.spec.serviceAccountName: rec" and "rec.spec.createServiceAccount: false" into your yaml definition._**

_If you require a different name, you must grant the SCC to the project namespace._

**Comment by mich-elle-luna** [comment]
Hi,

Thanks you for this suggestion, are you referring to this page? https://redis.io/docs/latest/operate/kubernetes/deployment/openshift/openshift-operatorhub/ 
Just want to be sure we update the right content.

-Michelle

**Comment by hmarrao** [comment]
Hello, Hope you are dogin well ...

yes that the page yes!!!

... thx ...

**Comment by kaitlynmichael** [comment]
The doc change for this issue was made in https://github.com/redis/docs/pull/684.
