### ISSUE TITLE
PSYNC Doc Page Contains Broken Link to Redis Replication Doc Page

### ISSUE THREAD

**Issue by cabrerakm** [redis/docs#128]
On the [PSYNC](https://redis.io/docs/latest/commands/psync/) doc page, there is a link to the Redis replication doc page. However, that link is broken. I believe the new link should be https://redis.io/docs/latest/operate/oss_and_stack/management/replication/.

**Comment by dwdougherty** [comment]
Thank you for your report. This will be fixed on our dev branch today and this issue will auto-close on merge.
