### ISSUE TITLE
Redis Insight v2.48.0, April 2024: Keys are not reliably sorted in Browser

### ISSUE THREAD

**Issue by vb-rob** [redis/docs#136]
Sorting by key name mostly sorts by key, but some rows are sorted incorrectly. Note the keys start at `01HW3`..., then `01HW5`..., then `01HW4`...

Similar behavior when sorting ASC or DESC.

I am using delimited keys, the full keys start with `conversations:01HW`...

This is new in 2.48.0; I've never noticed this issue before (using Redis Insight regularly for more than a year).

<img width="897" alt="Screenshot 2024-04-23 at 10 29 42" src="https://github.com/redis/docs/assets/93546760/0347f896-f5a9-44cd-b7cb-bfbafaa8c917">

**Comment by mich-elle-luna** [comment]
Thanks for this report, much appreciated! I've notified the team.

**Comment by ViktarStarastsenka** [comment]
@vb-rob , Redis Insight sorts by the entire number, not just by one character.
E.g. in your case, you have 3, 5, 40, 44, 45.

**Comment by vb-rob** [comment]
Ah. I thought that keys were strings, and would be lexicographically sorted. Those IDs are ULIDs, https://github.com/ulid/spec

Is attempting a natural sort of numbers embedded in a longer alphanumeric string expected behavior? I've seen it done for leading or trailing numbers, but never when surrounded by alphas.

**Comment by ViktarStarastsenka** [comment]
@vb-rob , actually, this makes sense.
we'll target to change the sorting with 2.50 (will be out at the end of May).

**Comment by dwdougherty** [comment]
Hi Rob. Looks like Viktar has this ticket sorted. If so, may I close it?

**Comment by vb-rob** [comment]
Of course. Thanks, all!
