### ISSUE TITLE
Install ncjourney.so

### ISSUE THREAD

**Issue by amansingh14** [redis/docs#164]
Hi Team,

I am running Redis 6.2.14 on centos9.

Can anyone help to install `ncjourney.so`

I followed the below commands to install Redis package
```
dnf install redis redis-devel 
```

but no modules found at `/usr/lib64/redis/modules/`

Thank you

**Comment by dwdougherty** [comment]
Hello Aman. If you're asking about how to load a Redis module, see the following:

https://redis.io/docs/latest/develop/reference/modules/

You might also try asking your question in the Redis Discord:

https://discord.gg/qJEDhydw

**Comment by dwdougherty** [comment]
I'm going to go ahead and close this ticket, as there doesn't appear to be a docs issue here.
