### ISSUE TITLE
Configure high availability for replica shards

### ISSUE THREAD

**Issue by prateekkej** [redis/docs#173]
There is a typo in the below mentioned paragraph ----

Enabling replica_ha configures the cluster to automatically **replace** the promoted replica on an available node. This automatically returns the database to a state where there are two copies of the data: the former replica shard which has been promoted to primary and a new replica shard.

The marked word should have been "replicate". 

The final understanding would be - Enabling replica_ha will automatically create a replica of a promoted replica on another node making sure that there is no single point of failure. 

Updated text ---

Enabling replica_ha configures the cluster to automatically **replicate** the promoted replica on an available node. This automatically returns the database to a state where there are two copies of the data: the former replica shard which has been promoted to primary and a new replica shard.

**Comment by mich-elle-luna** [comment]
Hi, thanks for this report, is this the page you are referring to? https://redis.io/docs/latest/operate/rs/databases/configure/replica-ha/
