### ISSUE TITLE
High availability and replication

### ISSUE THREAD

**Issue by prateekkej** [redis/docs#174]
https://redis.io/docs/latest/operate/rc/databases/configuration/high-availability/#dataset-size

> For Redis Cloud Essentials, the size of the plan you choose includes replication. Therefore, if you choose replication, the dataset size you can use is half of the stated plan size. For example, if you choose a 1GB plan, Redis allocates **512 GB** for the memory limit, and the other 512 MB for Replication.

The above mentioned paragraph says - Out of the mentioned 1GB, Redis allocates 512 GB for the memory limit and the other 512MB for replication. 

It should have been 512 **MB** and not 512 **GB**

The final text would have been - 

> For Redis Cloud Essentials, the size of the plan you choose includes replication. Therefore, if you choose replication, the dataset size you can use is half of the stated plan size. For example, if you choose a 1GB plan, Redis allocates **512 MB** for the memory limit, and the other 512 MB for Replication.

**Comment by mich-elle-luna** [comment]
Thanks for this report, much appreciated.
