### ISSUE TITLE
TOPK.LIST - The time complexity is wrong

### ISSUE THREAD

**Issue by ddubrava** [redis/docs#247]
Hi! It is stated [here](https://redis.io/docs/latest/commands/topk.list/) that TOPK.LIST is O(k), while there is a quick sort ([code](https://github.com/RedisBloom/RedisBloom/blob/master/src/topk.c#L216)) used to return the sorted list of items.

Before [these changes](https://github.com/RedisBloom/RedisBloom/commit/a435ae54ba315cf62116215126d5c0e985577fe9) the list wasn't sorted. Then, a sort was added and [unit tests](https://github.com/RedisBloom/RedisBloom/commit/a435ae54ba315cf62116215126d5c0e985577fe9#diff-dc088b2955868b1a74aaf4b69241544483c2ffffb67eb2a110a5570ce9dcdc14L114) were updated, while the documentation was not

**Comment by dwdougherty** [comment]
Hi @LiorKogan . Would you mind taking a look and commenting?

**Comment by LiorKogan** [comment]
Thanks again.

@dwdougherty I created a docs PR - please review https://github.com/redis/docs/pull/252
