### ISSUE TITLE
TLS

### ISSUE THREAD

**Issue by wuyc80** [redis/docs#259]
After I configure TLS: redis service cannot start, and it get this error in logs: 
# Redis version=7.0.12, bits=64, commit=00000000, modified=0, pid=2320, just started
# Configuration loaded
# Failed to load certificate: /etc/redis/server.crt: error:8000000D:system library::Permission denied
# Failed to configure TLS. Check logs for more info.
Configuration in redis.conf: 
tls-cert-file /etc/redis/server.crt
tls-key-file /etc/redis/server.key

server.crt and server.key are created by openssl. 
server.crt and server.key: owner: redis, group: root, permission 777. 

It is run in linux.

**Comment by dwdougherty** [comment]
Hello. You might try asking for assistance on the Redis Discord. There are lots of friendly people there who can help. Here's the invitation link: https://discord.gg/SYFn8EJV

**Comment by dwdougherty** [comment]
Closing. Feel free to re-open with more information.
