### ISSUE TITLE
CLIENT UNBLOCK - return value doc is misleading (Redis 7.2.4)

### ISSUE THREAD

**Issue by clickonetwo** [redis/docs#260]
As of Redis 7.2.4, if I block client 42 on a BRPOP (as in the docs), and then I do CLIENT UNBLOCK 42 in a different client, the return value is 1.  Whereas, if client 42 is not blocked, then doing CLIENT UNBLOCK 42 in a different client returns 0.

The docs on this return value are a bit unclear, but seem to suggest that the opposite will be true.  I suggest the following documentation change:

	Integer reply: 0 if the target client was not blocked, so this call had no effect.
	integer reply: 1 if the target client was unblocked as a result of this call.

I am happy to submit a PR with this change if desired.

**Comment by dwdougherty** [comment]
Thank you, Daniel. I'll take a look soon.

**Comment by dwdougherty** [comment]
Fixing this on the main branch. It will become visible once we merge main into latest.
