### ISSUE TITLE
Manage API tasks

### ISSUE THREAD

**Issue by adudhakawar** [redis/docs#277]
A task is an API operation that is performed asynchronously because it exceeds the time allowed for the synchronous request/response model.

Above sentence is duplicate.

Page Link - https://redis.io/docs/latest/operate/rc/api/get-started/manage-tasks/

Its there after page title and before example of API operations.

![Screenshot 2024-06-02 at 8 33 43 AM](https://github.com/redis/docs/assets/117714923/d05d95fc-f8e4-466c-91fa-5f2d36508a41)

**Comment by mich-elle-luna** [comment]
Thanks for this report, this is probably in the metadata description which appears on the page as well, so we should update the one on the page and keep the description.
