### ISSUE TITLE
pleRedis Insight configuration settings

### ISSUE THREAD

**Issue by kirtanWyn** [redis/docs#320]
how to connect my redis db to redis-insight

**Comment by dwdougherty** [comment]
Hello @kirtanWyn. There's information on how to connect your DB to Redis Insight [here](https://redis.io/docs/latest/develop/connect/insight/#connection-management) . Is there something else you needed?

**Comment by dwdougherty** [comment]
Closing. If there's something else you need, please either re-open this issue or file another.

You can always join the [Redis Discord channel](https://discord.gg/KPwTRKRa) for technical assistance.
