### ISSUE TITLE
Tokenization not working with JSON

### ISSUE THREAD

**Issue by juergsch** [redis/docs#384]
When using redisearch for JSON documents like `{"id":"456.00.0000"}`
`FT.SEARCH myIndex 456` delivers the document.
`FT.SEARCH myIndex 456\\.0` or `FT.SEARCH myIndex "456\\.0"` delivers no result tested with redisearch 2.10.3. 
Or did I misunderstood the mechanism? How to search for text fields containing "." characters?

**Comment by dwdougherty** [comment]
Hi @juergsch . Give the following a try.

`redis.cloud:6379> FT.SEARCH myIndex "@id:456.00.0000"`

If that doesn't work, please raise your issue on [our Discord channel](https://discord.gg/GudhP9YB). There are lots of friendly people there who can answer technical questions. This site is for reporting documentation issues.
