### ISSUE TITLE
Feedback: Redis configuration file example

### ISSUE THREAD

**Issue by huoxiaowei** [redis/docs#470]
Page https://redis.io/docs/latest/operate/oss_and_stack/management

在redis配置文件中 (In the Redis configuration file)：
# Set redis server/io threads to cpu affinity 0,2,4,6:
# server_cpulist 0-7:2
开启参数，应该配置物理核还是逻辑核？(When turning on parameters, should we configure physical cores or logical cores?)

**Comment by dwdougherty** [comment]
The question is: When turning on parameters, should we configure physical cores or logical cores?

**Comment by dwdougherty** [comment]
Hi @LiorKogan . Do you know if the following setting refers to CPUs or cores?

```
# It is possible to pin different threads and processes of Redis to specific
# CPUs in your system, in order to maximize the performances of the server.
# This is useful both in order to pin different Redis threads in different
# CPUs, but also in order to make sure that multiple Redis instances running
# in the same host will be pinned to different CPUs.
#
# Normally you can do this using the "taskset" command, however it is also
# possible to this via Redis configuration directly, both in Linux and FreeBSD.
#
# You can pin the server/IO threads, bio threads, aof rewrite child process, and
# the bgsave child process. The syntax to specify the cpu list is the same as
# the taskset command:
#
# Set redis server/io threads to cpu affinity 0,2,4,6:
# server-cpulist 0-7:2
```

**Comment by LiorKogan** [comment]
@oranagra

**Comment by oranagra** [comment]
yes, it means cores.

**Comment by dwdougherty** [comment]
@huoxiaowei See above for the answer. (答案见上文。via Google Translate).

**Comment by dwdougherty** [comment]
Hi @huoxiaowei . I'm closing this ticket as it appears to be addressed. If that turns out not to be the case, feel free to re-open with a more complete description.

Thank you.
