### ISSUE TITLE
Redis CLI in Examples sections fails to load 

### ISSUE THREAD

**Issue by Re1nGer** [redis/docs#481]
I'm not sure if it's expected, but currently redis cli in Examples section fails to load properly and gives 503 
![image](https://github.com/user-attachments/assets/c1a38765-8b14-4d62-9ebb-ae2e99796268)

Such behavior is consistent in both Firefox and Google Chrome browsers

**Comment by dwdougherty** [comment]
Thank you for raising this to our attention, @Re1nGer . It might take a bit to restore the service that supports this capability, but we'll do so as soon as possible.

**Comment by dwdougherty** [comment]
This is fixed now. Thanks again, @Re1nGer, for the report. Much appreciated!

**Comment by Re1nGer** [comment]
Thank you, @dwdougherty for prompt response and action
