### ISSUE TITLE
 Issue with ES Module Import for redis-om Library

### ISSUE THREAD

**Issue by arnab316** [redis/docs#557]
Page https://redis.io/docs/latest/integrate/redisom-for-node-js/  
I'm encountering an issue when trying to import Entity and Schema from the redis-om library using ES module syntax in my project. Despite following the recommended practices for importing CommonJS modules into ES modules, I am still facing errors.
```
import { Entity, Schema } from 'redis-om';
         ^^^^^^
SyntaxError: Named export 'Entity' not found. The requested module 'redis-om' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:
```
- Attempt to import Entity and Schema from the redis-om library using the following ES module syntax:

`import { Entity, Schema } from 'redis-om';`

- Receive the syntax error as shown above.

- As an alternative, I tried importing the package as a default import and destructuring:
`import pkg from 'redis-om';
const { Entity, Schema } = pkg;
`
- This approach also resulted in the same error.

**Comment by dwdougherty** [comment]
Hi @arnab316 . I'm able to reproduce this. What I suggest you do is to reach out on our [Discord channel](https://discord.gg/AP4Hvs4b). One of the maintainers of the redis-om library is a frequent contributor there and I'm sure he can help you out. I will also ping him separately.

**Comment by dwdougherty** [comment]
I'm not expecting any further activity, so I'm closing this ticket.
