### ISSUE TITLE
Feedback: Redis hashes Expiration - Typo in keys and Error in return values

### ISSUE THREAD

**Issue by aneroid** [redis/docs#594]
Page https://redis.io/docs/latest/develop/data-types/hashes

For the "Field expiration examples", the code has a typo, note the upper-case **B** for `'Battery_level'`:

```py
event = {
    'air_quality': 256,
    'Battery_level':89
}

client.hset('sensor:sensor1', mapping=event)
```

So when doing the 'set expiration' step, it's setting it for a field which doesn't exist, note the lower-case **b** for `'battery_level'`:
```py
# set the TTL for two hash fields to 60 seconds
client.hexpire('sensor:sensor1', 60, 'air_quality', 'battery_level')
```

And when retrieving the TTL, this code would return TWO values in a list, not one. If the field doesn't exist, [the return value is `-2`](https://redis.io/docs/latest/commands/httl/); and the number of values in the list corresponds to the number of fields being checked.

Given code (incorrect):
```py
ttl = client.httl('sensor:sensor1', 'air_quality', 'battery_level')
print(ttl)
# prints [60]
```

should be:
```py
ttl = client.httl('sensor:sensor1', 'air_quality', 'battery_level')
print(ttl)
# prints [60, -2]
```

However, it would be better to fix the `event` dict to have the **correct field names**:
```py
event = {
    'air_quality': 256,
    'battery_level':89
}
```

and the corresponding code for the multiple fields' TTL retrieval would be:
```py
# set the TTL for two hash fields to 60 seconds
client.hexpire('sensor:sensor1', 60, 'air_quality', 'battery_level')
ttl = client.httl('sensor:sensor1', 'air_quality', 'battery_level')
print(ttl)
# prints [60, 60]
```

Side note: that page uses the variable name `r` for the redis connection for most of the start of the page but then uses `client` for the expiration examples without initialising `client` anywhere. This is not consistent and may be confusing.

**Comment by dwdougherty** [comment]
Thank you, @aneroid . I'll get this corrected.
