### ISSUE TITLE
Feedback: Run Redis Stack on Docker29910404

### ISSUE THREAD

**Issue by fultrim** [redis/docs#610]
Page https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker

**Comment by dwdougherty** [comment]
Hi @fultrim . It's not clear to us why you opened this issue. Would you please provide some additional information?

**Comment by fultrim** [comment]
I am so sorry.  bobot posted this here and that was a mistake.

**Comment by dwdougherty** [comment]
No worries! Thank you.
