### ISSUE TITLE
Feedback: Configure CIDR allow list

### ISSUE THREAD

**Issue by Rishi-Redis** [redis/docs#645]
Page https://redis.io/docs/latest/operate/rc/security/cidr-whitelist

"To use the CDIR allow list, you must be on either paid Redis Cloud Essentials or on Redis Cloud Pro. This feature is not supported on free Redis Cloud Essentials plans."

Should say "CIDR" instead.

**Comment by cmilesb** [comment]
Thanks for letting us know, @Rishi-Redis! I just opened a PR to fix this typo.
