### ISSUE TITLE
Feedback: CommandOverrider

### ISSUE THREAD

**Issue by PA-MOREY** [redis/docs#658]
Page https://redis.io/docs/latest/operate/oss_and_stack/stack-with-enterprise/gears-v1/jvm/classes/readers/commandoverrider

This code seems incorrect, is it expected to get HSET in the overridden command? Doesn't it create a loop?

**Comment by dwdougherty** [comment]
Just curious: Did you run the example yourself? I haven't done so yet, but that's the next step.

**Comment by dwdougherty** [comment]
No worries. I'm going to dig into this, but I probably won't get to it until next week. Stay tuned.

**Comment by dwdougherty** [comment]
Thanks for the help getting to a working solution. Docs PR is ready to be reviewed (doc peer) and then I will merge it.
