### ISSUE TITLE
Code selection does not persist for Redis Cli and C#

### ISSUE THREAD

**Issue by vishalg8454** [redis/docs#659]
The preference of code selection for Redis Cli and C# does not persist upon refresh. This is probably across the docs but I it's confirmed to be broken at https://redis.io/docs/latest/develop/get-started/data-store/ . Apparently the local store in not getting updated and we have some error in console as well. 

![image](https://github.com/user-attachments/assets/86dd8839-ae98-4851-b1c1-2947d33b33e6)

reproduction video below

[Uploading Redis bitmaps _ Docs - Google Chrome 2024-09-11 23-43-17.mp4…](https://github.com/user-attachments/assets/02267f41-5f64-4d28-b361-6c667986a64c)

**Comment by dwdougherty** [comment]
Hi @vishalg8454 .  Thank you for the report. I can reproduce this. Seems only C# is affected, but more testing to do.
