### ISSUE TITLE
Recurring Boolean field in Redis json key value breaks document in index

### ISSUE THREAD

**Issue by shashirangam** [redis/docs#668]
Hi,

Page [Redis-indexing document](https://redis.io/docs/latest/develop/interact/search-and-query/indexing/)

There is an open issue in stack over flow regarding **"Recurring Boolean field in Redis json key value breaks document in index"**. Is there any solution for this one. I am also facing same issue. Recently we implemented Redis-search in our spring boot application, but stuck with this limitation. Thank you in advance for your quick response.

Link: [Recurring Boolean field in Redis json key value breaks document in index](https://stackoverflow.com/questions/77557290/recurring-boolean-field-in-redis-json-key-value-breaks-document-in-index)

**Comment by mich-elle-luna** [comment]
Hello,

I tried to find a solution with our chat app
https://redis.io/chat

When dealing with recurring boolean fields in JSON arrays in Redis, you may encounter issues if trying to index and search them as TAG fields. Below is a recommended approach to properly index and search these boolean fields.
Sample JSON Document:

{
  "ACompanies": [
    { "APurchaseNeed": true, "Name": "Company1" },
    { "APurchaseNeed": false, "Name": "Company2" },
    { "APurchaseNeed": true, "Name": "Company3" }
  ]
}



Steps to Create the Index and Search:

    Create the Index: Use the JSONPath wildcard operator to handle multiple nodes in arrays.

   FT.CREATE myIndex ON JSON PREFIX 1 doc: SCHEMA $.ACompanies[*].APurchaseNeed AS APurchaseNeed TAG



    Add the Document:

   JSON.SET doc:1 $ '{"ACompanies":[{"APurchaseNeed":true,"Name":"Company1"},{"APurchaseNeed":false,"Name":"Company2"},{"APurchaseNeed":true,"Name":"Company3"}]}'



    Search the Document:

   FT.SEARCH myIndex "@APurchaseNeed:{true}"


Important Points:

    Using JSONPath Wildcard: The key part is using the wildcard in the JSONPath ($.ACompanies[*].APurchaseNeed) to index every occurrence of APurchaseNeed within the array items.
    Boolean as TAG: Tagging boolean values ensures that each APurchaseNeed is correctly indexed and can be searched efficiently.

By following these steps, you should be able to index and search recurring boolean fields within JSON arrays without issues.

For further details, refer to the [Redis documentation on indexing JSON arrays](https://redis.io/docs/latest/develop/interact/search-and-query/indexing).

**Comment by shashirangam** [comment]
Thanks for the quick response. I have tried the same as mentioned, but it doesn't worked for me. Here I am attaching the video for reference. 
Below command also giving no results
`FT.SEARCH myIndex *`
![image](https://github.com/user-attachments/assets/1d1b6e9f-480b-41e9-b33a-6a0f09bc358c)

I am using the redis-stack latest version using docker

`docker run -d --name redis-stack -p 6379:6379 -p 8001:8001 -v "D:/storage:/data:rw" redis/redis-stack:latest`

If I am not using the version which works fine for the solution provided, Please guide me to use the right version.
Thank you in advance for your quick response.

https://github.com/user-attachments/assets/74fa2e0c-bf95-49d3-a33c-abf4f345c316

**Comment by shashirangam** [comment]
Seems this issue resolved in redis-om-python **but not working with direct Redis queries**.
[Reference link for the similar issue](https://github.com/redis/redis-om-python/issues/510)
Can you reply me when it is going to fix.

**Comment by mich-elle-luna** [comment]
Hello again,

Sorry for the delay, I think you may have better luck getting help with your question on our discord server. Here are the instructions to join and ask your question/get help to solve your issue: https://redis.io/learn/community/discord

**Comment by dwdougherty** [comment]
I'm not expecting any further activity, so I'm closing this ticket.
