### ISSUE TITLE
Feedback: Manage clusters

### ISSUE THREAD

**Issue by JeffreyGroves** [redis/docs#669]
Page https://redis.io/docs/latest/operate/rs/clusters/

I don't see how to reference documentation for older versions of Redis Enterprise.
I see that the link above has `/latest/` within it, but I have already forgotten how to change this to reference a specific version.

**Comment by mich-elle-luna** [comment]
Hi,
We have the archive links here if that is what you are looking for? https://redis.io/docs/latest/operate/rs/rs-archive/

With the next version of Redis Enterprise, we will have a version selector on the new docs web site. 
Thanks,
Michelle
