### ISSUE TITLE
Feedback: Redis functions, call function from script?

### ISSUE THREAD

**Issue by tamasgyenese** [redis/docs#716]
Hi Redis Team!
After reading about Redis functions [here](https://redis.io/docs/latest/develop/interact/programmability/functions-intro/) an idea came to my mind, but I'm not sure it's possible or not, or I was trying to do it in a wrong way. Currently I have a lua script file, which contains a lot of commonly used functions, but to use it in other script, I have to concatenate them and load the result into the script cache, which is not the most efficient way.
Is it possible to call a function from a script?

I was trying to do that in that way using java/jedis:

 ```java
 private static final String MY_LIB = """
            #!lua name=mylib
                        
            local function my_hgetall(keys)
             return redis.call('HGETALL', keys[1])
            end
                        
            redis.register_function('my_hgetall', my_hgetall)
            """;

    private static final String TEST = """           
            local key = KEYS[1]
           
            return redis.call('FCALL', 'my_hgetall', key)

            """;

    public static void main(String[] args) {
      try (Jedis jedis = getOwmPool().getResource()){
          jedis.functionFlush();
          jedis.functionLoad(MY_LIB);
          Object eval = jedis.eval(TEST, List.of("hgetalltest"), List.of());
      }catch (Exception e) {
          System.out.println(e.getMessage());
      }
    }
```
But I got this error: ERR This Redis command is not allowed from script script:
Thanks, Tamas

**Comment by dwdougherty** [comment]
Hi @tamasgyenese . I think you would be better served if you asked your question on our [Discord channel](https://discord.gg/mtDrx4zx). There are lots of friendly technical folks there to help.
