### ISSUE TITLE
Feedback: Redis Streams, documentation on Consumer Groups persistence

### ISSUE THREAD

**Issue by GovindarajanNagarajan-TomTom** [redis/docs#729]
Page https://redis.io/docs/latest/develop/data-types/streams

Hi,

We have an application relying on Redis that we deploy on a Kubernetes cluster. We have a persistent volume mounted on our Redis container and a snapshot is written to the container every 60 secs. 

Our Redis container is at times restarted and we notice that the streams and messages in the streams are persisted. However, one of our engineers mentioned that the consumer groups created by the consumers are not persisted, so the application starts crashing because it holds a reference to a Consumer Group that no longer seems to exist.

The [wording](https://redis.io/docs/latest/develop/data-types/streams/#persistence-replication-and-message-safety) about Persistence is a bit confusing. It looks like Streams are persisted, but are Consumer Groups persisted as well ? If so, are they persisted in both snapshot (rdb) and AOF persistences or only in AOF persistence ?

**Comment by mich-elle-luna** [comment]
Hello,
I asked Redis [copilot](https://redis.io/chat) your question and it provided this answer: "Yes, Consumer Groups in Redis Streams are persisted. They are persisted in both RDB (Snapshot) and AOF (Append Only File) persistence methods. This ensures that your Consumer Group metadata, including the pending entries list and last delivered ID for each consumer, are saved and can be reconstructed if the server is restarted or crashes."
[Configure database persistence](https://redis.io/docs/latest/operate/rs/databases/configure/database-persistence)[Data persistence] (https://redis.io/docs/latest/operate/rc/databases/configuration/data-persistence)[Redis persistence](https://redis.io/docs/latest/operate/oss_and_stack/management/persistence) [Streams in Active-Active databases](https://redis.io/docs/latest/operate/rs/databases/active-active/develop/data-types/streams) [Considerations about Consistency and Data Loss in a CRDB Regional Failure](https://redis.io/kb/doc/21rbquorvb/considerations-about-consistency-and-data-loss-in-a-crdb-regional-failure) If you have other questions, you can also try asking on our (discord)[https://redis.io/learn/community/discord]

**Comment by dwdougherty** [comment]
Closing as answered. Feel free to re-open if you need further clarification.
