### ISSUE TITLE
Feedback: Install Redis on Linux (install a specific version)

### ISSUE THREAD

**Issue by collimarco** [redis/docs#734]
Page https://redis.io/docs/latest/operate/oss_and_stack/install/install-redis/install-redis-on-linux

I have Ubuntu 22.04 LTS and the default version shipped with it is Redis 6.0. How can you update to Redis 7.x?

The documentation describes how to install always **the latest version**, but that is not ideal for a production environment. How can you update and **lock to a specific major version** (e.g. update to 7.x, but avoid automatic updates to 8.x in the future).

**Comment by dwdougherty** [comment]
First, add the repository to the APT index and update it as shown in the docs:

```
sudo apt-get install lsb-release curl gpg
curl -fsSL https://packages.redis.io/gpg | sudo gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
sudo chmod 644 /usr/share/keyrings/redis-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/redis.list
sudo apt-get update
```

You can then list the available Redis versions using the following command:

```
$ sudo apt-cache policy redis
redis:
  Installed: (none)
  Candidate: 6:7.4.1-1rl1~jammy1
  Version table:
     6:7.4.1-1rl1~jammy1 500
        500 https://packages.redis.io/deb jammy/main amd64 Packages
        500 https://packages.redis.io/deb jammy/main all Packages
     6:7.4.0-1rl1~jammy1 500
        500 https://packages.redis.io/deb jammy/main amd64 Packages
        500 https://packages.redis.io/deb jammy/main all Packages
     6:7.2.6-1rl1~jammy1 500
        500 https://packages.redis.io/deb jammy/main amd64 Packages
        500 https://packages.redis.io/deb jammy/main all Packages
...
```

To install, say, Redis 7.4.1, run

```
$ sudo apt-get install redis=6:7.4.1-1rl1~jammy1

...

$ redis-cli --version
redis-cli 7.4.1
```

You should consult other sources (e.g., Stackoverflow) to inquire about freezing packages; i.e., preventing future updates. 

Hope that helps.

**Comment by dwdougherty** [comment]
Closing as answered. Feel free to re-open if you need further clarification on the information in our docs.
