### ISSUE TITLE
Feedback: C# .NET Core

### ISSUE THREAD

**Issue by M-Yankov** [redis/docs#740]
When search in google: "Redis .NET CORE" the [page](https://redis.io/learn/develop/dotnet/aspnetcore/caching/basic-api-caching) is the first result and pointing to a wrong library (`StackExchange.Redis`) (_at least I wanted to use JSON() methods_, but they don't exist), I even cannot navigate to that page from the Web Interface ? ¯\\\_(ツ)_/¯  

The confusion comes from that https://redis.io/docs/latest/develop/connect/clients/dotnet/ says to install `NRedisStack`

Can you remove the **Basic Api cache page** from the search results in Google or at least fix the example?

**Comment by mich-elle-luna** [comment]
Thanks for this feedback, I will let the owners of this page know about it so they can make the update.
