### ISSUE TITLE
Feedback: Connection management commands compatibility

### ISSUE THREAD

**Issue by yoavredis** [redis/docs#742]
Page https://redis.io/docs/latest/operate/rs/references/compatibility/commands/connection

Hi @rrelledge,
This page needs a minor change for the notes of the SELECT command, as follows:

Current:
"Redis Enterprise does not support shared databases due to potential negative performance impacts and blocks any related commands"

New:
"Redis Enterprise does not support shared databases due to potential negative performance impacts and blocks any related commands. The SELECT command is supported solely for compatibility with Redis Community Edition, but it does not perform any operation in Redis Enterprise."

**Comment by rrelledge** [comment]
Thanks, @yoavredis. I opened a ticket for this: DOC-4359
