### ISSUE TITLE
Can't install docs with latest hugo

### ISSUE THREAD

**Issue by Pyr0Texn1c** [redis/docs#743]
[redis-doc-7.4.1-2024_10_09_14_05_32.log](https://github.com/user-attachments/files/17307808/redis-doc-7.4.1-2024_10_09_14_05_32.log)
[redis-doc-7.4.1-2024_10_09_14_42_42.log](https://github.com/user-attachments/files/17307809/redis-doc-7.4.1-2024_10_09_14_42_42.log)
[redis-doc-7.4.1-2024_10_09_14_35_33.log](https://github.com/user-attachments/files/17307810/redis-doc-7.4.1-2024_10_09_14_35_33.log)
[redis-doc-7.4.1-2024_10_09_14_21_45.log](https://github.com/user-attachments/files/17307811/redis-doc-7.4.1-2024_10_09_14_21_45.log)
[redis-doc-7.4.1-2024_10_09_14_11_47.log](https://github.com/user-attachments/files/17307812/redis-doc-7.4.1-2024_10_09_14_11_47.log)

**Comment by Pyr0Texn1c** [comment]
Workaround to overcome make errors in first 4 logfiles (by date):
[redis-docs.workaround.txt](https://github.com/user-attachments/files/17308069/redis-docs.workaround.txt)

**Comment by dwdougherty** [comment]
Hi @Pyr0Texn1c . The README.md file on this site lists the prerequisites, and "Hugo site generator, v0.111.2; the extended edition" is required. We're aware that we're using an older version of Hugo, but we don't consider this to be a site bug.
