### ISSUE TITLE
Feedback: StackExchange.Redis.RedisServerException: 'ERR unknown command 'FT.CREATE''

### ISSUE THREAD

**Issue by jade507751** [redis/docs#786]
Getting StackExchange.Redis.RedisServerException: 'ERR unknown command 'FT.CREATE'' while calling  ft.Create(
     "idx:users",
     new FTCreateParams().On(IndexDataType.JSON).Prefix("user:"),
     schema);

**Comment by mortensi** [comment]
Please verify that you are using one of the following. 

- Redis Stack
- Redis 8 M01 (right now the only milestone available)
- A [Redis Cloud](https://redis.io/try-free/) database

Redis CE 7.4 or earlier versions do not have the search commands onboard. From Redis 8 on, all the search capabilities will be packed in Redis.
