### ISSUE TITLE
Feedback: SMISMEMBER

### ISSUE THREAD

**Issue by RichardWright** [redis/docs#796]
Page https://redis.io/docs/latest/commands/smismember/

There is a lack of information on the limitation of members which can queried here. Could this be confirmed and updated?

**Comment by dwdougherty** [comment]
The limit is dictated by the Redis protocol, which caps the maximum argument size for any command at 512 MB per request. So, there really isn't a specific limit for the number of arguments that can be passed to variadic commands like SMISMEMBER, and the reason why this isn't called out for each such command.

Practically speaking, many thousands of arguments can often be passed in one request, as long as they do not exceed the payload limit.
