### ISSUE TITLE
404 page for Documentation

### ISSUE THREAD

**Issue by eugene-at** [redis/docs#859]
<img width="1462" alt="Screenshot 2024-11-09 at 15 18 21" src="https://github.com/user-attachments/assets/a7afb343-b9a8-49a1-92ff-75e71c5eed05">

**Comment by eugene-at** [comment]
> Hi @eugene-at. What page where you on when you clicked this broken link?

Still reproduced for Download Redis Insight popup page

<img width="1785" alt="Screenshot 2024-11-12 at 19 54 08" src="https://github.com/user-attachments/assets/b085dd0f-90df-4c1a-b4c8-df3dc1727df4">

**Comment by dwdougherty** [comment]
Okay. We don't own that content (can't modify it), but I'll reach out to the team who does.

**Comment by dwdougherty** [comment]
I reached out to the team and they acknowledged. I'm going to go ahead and close this ticket, since I won't see any commits in this repo. Thanks again, @eugene-at !

**Comment by dwdougherty** [comment]
I reached out to the team and they acknowledged. I'm going to go ahead and close this ticket, since I won't see any commits in this repo. Thanks again, @eugene-at !
