### ISSUE TITLE
Feedback: Redis pipelining

### ISSUE THREAD

**Issue by hLanceNuro** [redis/docs#894]
Page https://redis.io/docs/latest/develop/use/pipelining/

Could we label the axes on this plot in the page:
![image](https://github.com/user-attachments/assets/694a17d3-b2a8-401d-ac9b-a7c002525f99)

**Comment by dwdougherty** [comment]
Thank you, @hLanceNuro . Fixed.

**Comment by hLanceNuro** [comment]
Thanks @dwdougherty!
