### ISSUE TITLE
Feedback: Access management - user with "Member" Role

### ISSUE THREAD

**Issue by lihi-atzmoni-redis** [redis/docs#940]
Page https://redis.io/docs/latest/operate/rc/security/access-control/access-management

According to the documentation, a user with the Member role can create a database (without any cost impact). However, this option is no longer valid, as it is currently not possible to create a new database without creating a new subscription. Therefore, a user with the Member role cannot create a database anymore.

**Comment by joniredis** [comment]
AFAIK this should indeed still be possible.

**Comment by cmilesb** [comment]
In that case, the docs are still correct, so I'm going to close this issue.

**Comment by lihi-atzmoni-redis** [comment]
<img width="1532" alt="image" src="https://github.com/user-attachments/assets/bee9b24d-7f6b-4409-b8f9-113d71f3a190">
User with "Member" role cant add databases to Pro subscriptions

**Comment by cmilesb** [comment]
@joniredis Is this the intended behavior?

**Comment by lihi-atzmoni-redis** [comment]
Currently a Member cant add databases to Pro subscriptions
![image](https://github.com/user-attachments/assets/d2ed404f-dc58-4d18-b70a-43beb98fde39)
