### ISSUE TITLE
Feedback: Redis Streams

### ISSUE THREAD

**Issue by RyanCheungJF** [redis/docs#953]
Page https://redis.io/docs/latest/develop/data-types/streams

For Java, since the code syntax is rather verbose, the code example stretches past the limit of the display box. 

However, the box is not scroll-able sideways, thus the reader is unable to view the full code block.

![image](https://github.com/user-attachments/assets/2fd4e55c-9731-453e-a1ba-b1ddc46cd7ac)

**Comment by dwdougherty** [comment]
Thank you, @RyanCheungJF. We'll take a look to see if there's an easy fix.

**Comment by dwdougherty** [comment]
Hi again, @RyanCheungJF. There's no quick fix that I can see; I'll need to get a front-end developer to take a look. I've opened an internal ticket for this, and I would prefer to close this external ticket if that's okay. Let me know.

**Comment by RyanCheungJF** [comment]
Sure thing @dwdougherty, thanks for checking it out!
