### ISSUE TITLE
Feedback: TTL

### ISSUE THREAD

**Issue by charity1475** [redis/docs#958]
Page https://redis.io/docs/latest/commands/ttl/

Based on TTL values we foresee Redis to be as the best notification engine. 
Currently, we are sure that Redis tracks TTL for deletion, and therefore we can have a feature that:
When the TTL countdown goes to 0 before deletion, the object (key| filed) is sent to a callback endpoint, and then a record is deleted. Some kind of dispatch/notify before delete.

**Comment by dwdougherty** [comment]
Thank you for reaching out, @charity1475. I suggest you add your request to one of the two places listed below:

- https://github.com/redis/redis/issues
- https://github.com/redis/redis/discussions
