### ISSUE TITLE
Feedback: Bloom filter

### ISSUE THREAD

**Issue by yeoleobun** [redis/docs#959]
Page https://redis.io/docs/latest/develop/data-types/probabilistic/bloom-filter
The formula of `bits_per_item` is incorrect 

https://github.com/redis/docs/blob/a0ed5991bd15023aaf5beb50d2e47ef65dfc17f0/content/develop/data-types/probabilistic/bloom-filter.md?plain=1#L131

According wikipedia [Optimal_number_of_hash_functions](https://en.wikipedia.org/wiki/Bloom_filter#Optimal_number_of_hash_functions), bits per item is: $-\frac{\ln(\epsilon)}{{\ln(2)}^2}$ ($\epsilon$ is error rate).

And the formula in the doc $-\frac{\ln(\epsilon)}{\ln(2)}$ is actually the optimal number of hash functions.

I calculate with python `-log(error_rate) / (log(2) ** 2)` get 9.58, 14.37, 19.17 for error rate 1 %, 0.1 %, 0.01% respectly.

**Comment by dwdougherty** [comment]
@LiorKogan Would you mind commenting on this issue?

**Comment by LiorKogan** [comment]
@yeoleobun thank you for spotting this! You are correct of course. We will fix this soon.
